version: "3.9"
services:
  signal-rating:
    image: ghcr.io/andrew-phillips-alpine/signal-rating:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

